version: "3"
services:
  postgres:
    container_name: conta_postgres_container
    image: postgres:15.3-alpine3.18
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - 5432:5432
